- name: Install Emulators
  hosts: localhost
  become: true
  tasks:
    - name: Update local packages first
      pacman:
        upgrade: yes
    
    - name: install RetroArch
      pacman: 
        name: 
          - retroarch
          - gamemode
          - libretro-overlays
          - libretro-shaders
          - retroarch-assets-xmb
          - libretro-core-info
          - libretro-shaders-slang
          - libretro-beetle-pce
          - libretro-blastem
          - libretro-core-info
          - libretro-gambatte
          - libretro-melonds
          - libretro-mupen64plus-next
          - libretro-play
          - libretro-shaders-slang
          - libretro-beetle-pce-fast
          - libretro-bsnes
          - libretro-database-git
          - libretro-genesis-plus-gx
          - libretro-mesen
          - libretro-nestopia
          - libretro-ppsspp
          - libretro-snes9x
          - libretro-beetle-psx
          - libretro-bsnes2014
          - libretro-desmume
          - libretro-kronos
          - libretro-mesen-s
          - libretro-overlays
          - libretro-retrodream
          - libretro-stella2014-git
          - libretro-beetle-psx-hw
          - libretro-bsnes-hd
          - libretro-dolphin
          - libretro-mame
          - libretro-scummvm
          - libretro-meta
          - libretro-parallel-n64
          - libretro-sameboy
          - libretro-yabause
          - libretro-beetle-supergrafx
          - libretro-citra
          - libretro-flycast
          - libretro-mame2016
          - libretro-mgba
          - libretro-picodrive
        state: present
    
    - name: install DOSBox
      pacman:
        name: dosbox
        state: present
    

    - name: download RetroArch mandatory Bioses
      shell: wget https://github.com/Abdess/retroarch_system/archive/refs/heads/libretro.zip && unzip libretro.zip && rm libretro.zip

    - name: place RetroArch Bioses into correct repertory
      shell: mv retroarch_system-libretro/*/* /home/*/.config/retroarch/system/ && rm -r retroarch_system-libretro && chmod -R 755 /home/*/.config/retroarch/system/